### ISSUE TITLE
Finish writing the marriage-length-tracker copy and launch it

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/how-long#3]
And any other fixes necessary on the markup before launch. Once it's ready to go put it up on prod so we have it ready to promote on / after the wedding day.

**Comment by freejoe76** [comment]
Note that I fixed up some metadata today and changed the directory name for SEO purposes.

**Comment by freejoe76** [comment]
Also note that this is the priority ticket this is the number one numero uno yea yea yea.

**Comment by kelliparker** [comment]
Markup is updated. Will push to prod in the a.m.

**Comment by kelliparker** [comment]
It's up!
