### ISSUE TITLE
When there is 1 day or 1 hour or 1 minute or 1 second, the label should be singular

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/how-long#4]
<img width="653" alt="screen shot 2018-05-17 at 9 49 19 am" src="https://user-images.githubusercontent.com/125554/40181692-b154ebb8-59b7-11e8-96f3-8f1f22f43643.png">

**Comment by kelliparker** [comment]
I got this done after some frustrating, Joe-hating, Javascript-cursing good times. Let me know what you think.
